### ISSUE TITLE
Card formatting bugs

### ISSUE THREAD

**Issue by trevormeier** [imdone/imdone#17]
macOS 10.15.3 imdone 1.4.18

1. Checkboxes are mis-aligned with other text (too far to the left)
2. Paragraphs following lists are mis-aligned (indented with list items)

![Screen Shot 2020-03-04 at 2 47 04 PM](https://user-images.githubusercontent.com/4143559/75907469-1b1f6800-5e27-11ea-8df2-66ee9fffff7c.png)

The card text is:

```
Research tripods
Which one fits best for carry-on?
- [ ] Peak design
- [ ] Gitzo latest
- [x] Acratech video head
Also needs to support up to 8kg
```

3. The "more" icon takes up a whole line of space in the card, especially noticeable when there are tags (see screenshot). If you are going to look at this issue, I generally find the "more" icon an insufficient indicator that there's more content in a card than what's visible. It would be nice to have a subtle affordance that's easier to notice at a glance when reading a card to indicate there's more content. 

![Screen Shot 2020-03-04 at 2 53 16 PM](https://user-images.githubusercontent.com/4143559/75908134-55d5d000-5e28-11ea-99e9-16fe0b0bc9ac.png)

**Comment by piascikj** [comment]
@trevormeier I think 1 and 3 are addressed in the latest release.  I'd love to hear your feedback.  On number 2, since markdown requires a new line in between a list and a paragraph, you can use an empty comment to achieve the same.  For example...
```
Research tripods
Which one fits best for carry-on?
- [ ] Peak design
- [ ] Gitzo latest
- [x] Acratech video head
<!--  -->
Also needs to support up to 8kg
```
Will render...
<img width="416" alt="Screen Shot 2020-04-03 at 8 40 54 AM" src="https://user-images.githubusercontent.com/233505/78372799-f41f9780-7586-11ea-84d4-4f908cfbf873.png">

To add a comment in the card editor you can use (cmd + /)

**Comment by piascikj** [comment]
Implemented
